#!/bin/bash
npm init --force --yes
npm install --save aws-sdk@^2.718.0
npm install --save axios@^0.19.2
npm install --save axios@^0.19.2
npm install --save syngenta-data-adapter@^1.7.1
npm install --save syngenta-database-versioner@1.3.4
npm install --save syngenta-lambda-client@^2.2.0
npm install --save uuid@^8.1.0
npm install --save-dev eslint@^7.5.0
npm install --save-dev eslint-config-airbnb@^18.1.0
npm install --save-dev eslint-config-airbnb-base@^14.1.0
npm install --save-dev eslint-config-prettier@^6.11.0
npm install --save-dev eslint-plugin-import@^2.20.2
npm install --save-dev eslint-plugin-jsx-a11y@^6.2.3
npm install --save-dev eslint-plugin-node@^11.1.0
npm install --save-dev eslint-plugin-prettier@^3.1.4
npm install --save-dev eslint-plugin-react@^7.20.0
npm install --save-dev eslint-plugin-react-hooks@^4.0.8
npm install --save-dev mocha@^8.0.1
npm install --save-dev prettier@^2.0.5
npm install --save-dev serverless@^1.72.0
npm install --save-dev serverless-offline@5.12.1
npm install --save-dev serverless-plugin-bind-deployment-id@~1.2.0
npm install --save-dev serverless-plugin-log-retention@^2.0.0
npm install --save-dev syngenta-cloud-tool@^1.4.